###########
# site.title

title:    'Torchlight'
subtitle: 'CS 175: Project in AI (in Minecraft) -- Building a Brighter Minecraft World!'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
